### PR TITLE
Move the client connector creation logic to init action

### LINKED ISSUE #4365: HTTP client connectors are created per request
**Description:**
HTTP client connectors are created per each request. This is unnecessary since the connector creation is mainly concerned with configuring the connector and is not concerned with the context surrounding a request. 

**Steps to reproduce:**
Run a simple Ballerina program containing an HTTP client connector and debug. The `getHTTPHttpClientConnector()` method in `HttpConnectionManager` which is responsible for creating a new HTTP client connector is called for each request.

**Affected Versions:**
0.95.x

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
Improvement

**Suggested Assignees (optional):**
Myself

### PR DESCRIPTION
**Pull request by pubudu91**
This PR moves the client connector creation logic from `HttpConnectionManager` to `Init`. This is to prevent the whole client connector creation process from being repeated per each request. 
 
Fix #4365

### CODE REVIEW

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java [hunk 1]
```diff
@@ -53,8 +76,130 @@ public ConnectorFuture execute(Context context) {
...
+
+        HttpConnectionManager connectionManager = HttpConnectionManager.getInstance();
+
+        String scheme;
+        if (url.startsWith("http://")) {
+            scheme = Constants.PROTOCOL_HTTP;
+        } else if (url.startsWith("https://")) {
+            scheme = Constants.PROTOCOL_HTTPS;
+        } else {
+            throw new BallerinaException("Malformed URL: " + url);
```
Comment (sameera-jayasoma) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: s/Malformed URL/ malformed URL/g

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java [hunk 2]
```diff
@@ -53,8 +76,130 @@ public ConnectorFuture execute(Context context) {
...
+
+        Map<String, Object> properties =
+                HTTPConnectorUtil.getTransportProperties(connectionManager.getTransportConfig());
+        SenderConfiguration senderConfiguration =
+                HTTPConnectorUtil.getSenderConfiguration(connectionManager.getTransportConfig(), scheme);
+
+        if (connectionManager.isHTTPTraceLoggerEnabled()) {
+            senderConfiguration.setHttpTraceLogEnabled(true);
+        }
+        senderConfiguration.setTlsStoreType(Constants.PKCS_STORE_TYPE);
```
Comment (sameera-jayasoma) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: setTLSStoreType

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java [hunk 3]
```diff
@@ -53,8 +76,130 @@ public ConnectorFuture execute(Context context) {
...
+        }
+
+        senderConfiguration.setFollowRedirect(followRedirect == TRUE);
+        senderConfiguration.setMaxRedirectCount(maxRedirectCount);
+        int enableChunking = options.getBooleanField(Constants.ENABLE_CHUNKING_INDEX);
+        senderConfiguration.setChunkEnabled(enableChunking == TRUE);
+
+        long endpointTimeout = options.getIntField(Constants.ENDPOINT_TIMEOUT_STRUCT_INDEX);
+        if (endpointTimeout < 0 || !isInteger(endpointTimeout)) {
+            throw new BallerinaConnectorException("Invalid idle timeout: " + endpointTimeout);
```
Comment (sameera-jayasoma) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: s/invalid idle timeout/invalid idle timeout/g

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java (hunk 1 above)
Comment (pubudu91) [reply modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: Ack.

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java (hunk 2 above)
Comment (pubudu91) [reply modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: This will have to come from the transport. Will change once a transport release goes on, with the API change.

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java (hunk 3 above)
Comment (pubudu91) [reply modules/ballerina-http/src/main/java/org/ballerinalang/net/http/actions/Init.java]: Ack.

**Comment by shafreenAnfar** [comment]
@anupama-pathirage @sameera-jayasoma - Since your concerns are addressed I am dismissing the reviews, so that we can merge the PR. This needs to be merged as soon as possible in order to avoid build breaks. 

Hope you guys don't mind :)
