### PR TITLE
Fix issue 'Restrict defining symbols declared in builtin package'

### LINKED ISSUE #3922: Restrict defining symbols declared in builtin package

### PR DESCRIPTION
**Pull request by hasithaa**
Resolves #3922

### CODE REVIEW

**Comment by sanjiva** [comment]
please fix this spelling: parseFunctoin

File: modules/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -751,9 +751,10 @@ public BVarSymbol defineVarSymbol(DiagnosticPos pos, Set<Flag> flagSet, BType va
 
         // Add it to the enclosing scope
         // Find duplicates
-        if (symResolver.checkForUniqueSymbol(pos, env, varSymbol, SymTag.VARIABLE_NAME)) {
-            enclScope.define(varSymbol.name, varSymbol);
+        if (!symResolver.checkForUniqueSymbol(pos, env, varSymbol, SymTag.VARIABLE_NAME)) {
+            varSymbol.type = symTable.errType;
```
Comment (sameera-jayasoma) [inline modules/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Even if the variable is redeclared, it has a type and we should use that type for subsequent expression analysis. Why did we change that?

File: modules/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -25,6 +25,9 @@ error.unused.import.package=\
 error.redeclared.symbol=\
   redeclared symbol ''{0}''
 
+error.redeclared.builtin.symbol=\
+  redeclared built-in symbol ''{0}''
```
[the remark this answers is not in the document]
Comment (hasithaa) [reply modules/ballerina-lang/src/main/resources/compiler.properties]: Fixed it.

File: modules/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 1 above)
Comment (hasithaa) [reply modules/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: @sameera-jayasoma. It causes to report uncertain errors for the following scenario. 

```
string error = "abc";

function main(string[] args){
    error err = { txt : "abc"};
}

struct error {
    string txt;
}
```
Following is the compilation result. 
```
error: pkg.bal:7:1: redeclared builtin symbol 'error'
error: pkg.bal:1:1: redeclared builtin symbol 'error'
error: pkg.bal:4:19: undefined field 'txt' in struct 'error'
error: pkg.bal:1:1: undefined symbol 'error'
```
Here error 3 is reported by resolving the builtin error, But that error depends on the program, so sometimes it can be correct, but sometimes not.  Additional it reports 4th error `undefined symbol 'error'` which is not correct. 

If the symbol is not unique, I have marked that symbol's type as an error type and then define. This will avoid uncertain errors. 

with this change following is the new compilation result. 

```
error: pkg.bal:7:1: redeclared builtin symbol 'error'
error: pkg.bal:1:1: redeclared builtin symbol 'error'
```
