### PR TITLE
Fix HTTP trace logs and introduce log level configuring

### LINKED ISSUE #3245: [Trace Logs] CLI parameter for enabling HTTP trace logs is hard coded
Due to an issue with JCommander, we had to hard code the flag for the run command as "-Bhttp-trace-log". Ideally we need to support flags of type "-Bhttp-trace-log" and "-Bhttp-trace-log=<destination>".

### PR DESCRIPTION
**Pull request by pubudu91**
This PR brings slight changes to how trace logs are used following the introduction of the config API. Now, to enable HTTP trace logs, users need to set the `-B[tracelog.http].level=DEBUG` flag. 

This also introduces log level configuring to Ballerina user level logging through the config API. There are several aspects to this: log API config vs. package level configs and `ballerina.conf` vs. dynamic parameters. 

If we consider dynamic parameters, log level can be set to the entire log API through the flag `-B[ballerina.log].level=<LOG_LEVEL>`. To set the log level to a specific package, 2 flags are required: one to specify the packages to which we are assigning configurations and another (for each specified package) to specify the log level. For example, consider packages `com.abc` and `com.xyz`:
```
ballerina run program.bal -Bballerina.log.instances=com.abc,com.xyz -B[com.abc].level=DEBUG -B[com.xyz].level=WARN
```
In the above example, all packages other than `com.abc` and `com.xyz` use the default log level (INFO).

Configurations can be set from a `ballerina.conf` config file as well. For example,
```
ballerina.log.instances=com.abc,com.xyz

[ballerina.log]
level=WARN

[com.abc]
level=INFO

[com.xyz]
level=DEBUG
```
The conf file can be placed in the same directory as the source or can be passed as a dynamic parameter through the `-Bballerina.conf=<FILE_PATH>` flag.

Fixes #3245

### CODE REVIEW

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpConnectionManager.java [hunk 1]
```diff
@@ -270,7 +272,9 @@ private void validateConnectorStartup(ConnectorStartupSynchronizer startupSyncer
     }
 
     private boolean isHTTPTraceLoggerEnabled() {
-        return System.getProperty(BLogManager.HTTP_TRACE_LOGGER) != null ? true : false;
+        // TODO: Take a closer look at this since looking up from the Config Registry here caused test failures
+        return ((BLogManager) LogManager.getLogManager()).getPackageLogLevel(
+                org.ballerinalang.logging.util.Constants.HTTP_TRACE_LOG) == BLogLevel.DEBUG;
```
Comment (hasithaa) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpConnectionManager.java]: is this DEBUG or TRACE ?

Comment (pubudu91) [reply modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpConnectionManager.java]: It's DEBUG. The name trace logs doesn't have anything to do with the log level

Comment (hasithaa) [reply modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpConnectionManager.java]: We have Trace logger. I think this should goto trace.
