### PR TITLE
Fix issue related to worker accessing message within resource

### LINKED ISSUE #2623: [workers] Error when there are two workers calling two other services
**Steps**
1. Run the below service with two workers, both calling two different endpoints
./ballerina run service <service1> <service2> <service3>

```
import ballerina.lang.system;
import ballerina.net.http;
import ballerina.lang.messages;

const int index = 12;

@http:BasePath {value:"/passthrough"}
service passthrough {

    @http:POST{}
    @http:Path {value:"/test1"}
    resource passthrough (message m) {

        //curl -v http://localhost:9090/passthrough/test1 -d '{"country":"Europe"}'

        message resultAirline = {};
        message resultHotel = {};

        m -> AirlineWorker;
        m -> HotelWorker;
        system:println("After workers");
        resultAirline <- AirlineWorker;
        resultHotel <- HotelWorker;
        system:println(result);
        string airline = messages:getStringPayload(resultAirline);
        string hotel = messages:getStringPayload(resultHotel);

        system:println("Message received from the worker - " + airline + " + " + hotel);

        string concat = airline + " " + hotel;
        message result = {};
        messages:setStringPayload(result, concat);
        reply result;

        worker AirlineWorker {
            message msg = {};
            message response = {};
            msg <- default;

            http:ClientConnector airline = create http:ClientConnector("http://localhost:9090/airline");
            response = http:ClientConnector.post(airline, "/book/Europe", msg);
            
            system:println("constant value is " + index);
            system:println("Message sent from the airline worker");
            response -> default;
        }

        worker HotelWorker {
            message msg = {};
            message response = {};
            msg <- default;

            http:ClientConnector hotel = create http:ClientConnector("http://localhost:9090/hotel");
            response = http:ClientConnector.post(hotel, "/book/europe", msg);

            system:println("constant value is " + index);
            system:println("Message sent from the hotel worker");
            msg -> default;
        }
    }
}
```

**Issue**
```
error in worker 'AirlineWorker': ballerina.lang.errors:Error, message: failed to invoke 'post' action in ClientConnector. null
        at ClientConnector.post(<native>:0)
        at passthrough.passthrough(TicketingService.bal:44)
ballerina.lang.errors:Error, message: unknown error occurred
        at passthrough.passthrough(TicketingService.bal:22)error in worker 'HotelWorker': ballerina.lang.errors:Error, message: failed to invoke 'post' action in ClientConnector. null
        at ClientConnector.post(<native>:0)
        at passthrough.passthrough(TicketingService.bal:61)
```

**Note**
It will work without errors when there is only one worker

### PR DESCRIPTION
**Pull request by chanakaudaya**
Fix #2623 #2732 #2619 #2715 #2763

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java [hunk 1]
```diff
@@ -249,6 +255,17 @@ public BMessage clone() {
...
             clonedMessage.setMessageDataSource(((BallerinaMessageDataSource) this.value.
                     getMessageDataSource()).clone());
+            isDataAdded = true;
+        }
+
+        // This code block is added to fix the bug related to workers when accessing message variable within
+        // resource. Fix #2623
+        if (!isDataAdded) {
+            try {
+                Thread.sleep(1);
```
Comment (sameera-jayasoma) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java]: Can you explain why do you need a thread sleep?

Comment (chanakaudaya) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java]: When workers are started within a resource, the message variable is accessible within those workers. By the time worker trying to access the content of the message, there is a chance that data is still not filled into the buffers within the message (since IO operations are running on a separate netty worker thread). Due to this reason, even though we clone the message and pass that to the worker, actual data is not available by the time we make the clone. Which means that workers will get messages with empty content.
Due to this reason, we are waiting here until the message content is added to the message through netty worker thread.

Comment (sameera-jayasoma) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java]: Thread sleep is not good :(

Comment (chanakaudaya) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java]: Will check for alternative approach.

Comment (chanakaudaya) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BMessage.java]: @sameera-jayasoma This is fixed with https://github.com/ballerinalang/ballerina/pull/2736/commits/afd7fea0f9523d24a94bd4f5fc0e59937bcf9fcc
