### PR TITLE
Fix build issues in windows

### LINKED ISSUE #2144: Maven build fails in windows environment
Affects v0.8.2 release tag.

### PR DESCRIPTION
**Pull request by SupunS**
Fix #2144

### CODE REVIEW

File: modules/annotation-processor/src/main/java/org/ballerinalang/natives/annotation/processor/ConstructProviderClassBuilder.java [hunk 1]
```diff
@@ -65,8 +65,8 @@
  */
 public class ConstructProviderClassBuilder {
     
-    private static final String SERVICES = "services" + File.separator;
-    private static final String META_INF = "META-INF" + File.separator;
+    private static final String SERVICES = "services/";
+    private static final String META_INF = "META-INF/";
```
Comment (SupunS) [inline modules/annotation-processor/src/main/java/org/ballerinalang/natives/annotation/processor/ConstructProviderClassBuilder.java]: using forward-slash instead of file separator, as this would be converted to system specific file-separator by the javax.annotation.processing.Filer,  by which this constant is used.
