### PR TITLE
Fix worker related issues. 

### LINKED ISSUE #3720: Using HTTP client connector inside fork-join worker will trigger join condition

### PR DESCRIPTION
**Pull request by hasithaa**
Fix #3720 
Fix #3710

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/ControlStackNew.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public StackFrame popFrame() {
             currentFrame = null;
             fp--;
         }
-
+        poppedFrame.markedAsReturned();
```
Comment (hasithaa) [inline modules/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/ControlStackNew.java]: rename to markAsReturned()
