### PR TITLE
Fixing the native functions to handle the error more gracefully

### LINKED ISSUE #1979: jms:acknowledge() util function gives java errors
Steps:
1. Deploy the following JMS service 
[my.txt](https://github.com/ballerinalang/ballerina/files/785135/my.txt)

2. Publish JMS text messages to the queue.
3. Check the service console

Note: Without jms:acknowledge(m,"AUTO_ACKNOWLEDGE"); line service works as expected

Issue: 
Observing following error on console
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run service /home/asankav/myarea/bal/Test/my.bal 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-1.5.10.wso2v1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-nop-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
ballerina: deploying service(s) in '/home/asankav/myarea/bal/Test/my.bal'

ballerina: started server connector http-9090

In Queue
error in ballerina program: 
	 at ballerina.net.jms:acknowledge(my.bal:17)
	 at onMessage1(my.bal:11)
	 at jmsWSO2MBQueueService(my.bal:9)

Exception in thread "pool-9-thread-1" org.ballerinalang.util.exceptions.BallerinaException: Cannot handle error using the error handler for : jms
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:135)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:100)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: 
	at org.ballerinalang.services.DefaultServerConnectorErrorHandler.handleError(DefaultServerConnectorErrorHandler.java:45)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:133)
	... 5 more
Caused by: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: 
	... 6 more

### PR DESCRIPTION
**Pull request by Megala21**
Fixes #1979

### CODE REVIEW

**Comment by Kishanthan** [comment]
Can you link this PR to the relevant issue?

**Comment by Megala21** [comment]
Linked the issue.

File: modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java [hunk 1]
```diff
@@ -48,14 +51,33 @@
...
 
-        if (ctx.getBalCallback() != null) {
-            carbonMessage.setProperty(JMSConstants.JMS_MESSAGE_DELIVERY_STATUS, deliveryStatus);
-            ctx.getBalCallback().done(carbonMessage);
+        if (null == jmsSessionAcknowledgementMode) {
+            log.warn("JMS Acknowledge function can only be used with JMS Messages. "
+                    + JMSConstants.JMS_SESSION_ACKNOWLEDGEMENT_MODE + " property is not found in the message.");
+            return VOID_RETURN;
+        }
+        if (JMSConstants.CLIENT_ACKNOWLEDGEMENT_MODE == (Integer) jmsSessionAcknowledgementMode) {
```
Comment (Kishanthan) [inline modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java]: Don't we need to check instance of before casting?

File: modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java [hunk 2]
```diff
@@ -48,14 +51,33 @@
...
         CarbonMessage carbonMessage = msg.value();
         String deliveryStatus = getArgument(ctx, 1).stringValue();
+        Object jmsSessionAcknowledgementMode = carbonMessage
+                .getProperty(JMSConstants.JMS_SESSION_ACKNOWLEDGEMENT_MODE);
 
-        if (ctx.getBalCallback() != null) {
-            carbonMessage.setProperty(JMSConstants.JMS_MESSAGE_DELIVERY_STATUS, deliveryStatus);
-            ctx.getBalCallback().done(carbonMessage);
+        if (null == jmsSessionAcknowledgementMode) {
+            log.warn("JMS Acknowledge function can only be used with JMS Messages. "
```
Comment (Kishanthan) [inline modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java]: Do we have to do a "WARN" here? If the property is optional, then we can check and act upon it, rather than do a "WARN"

Comment (Megala21) [inline modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java]: This property is not optional for jms messages, as the relevant property will be added for all the jms messages in the transport level. For other message types, if some user has mistakenly tried this, I think we need to give some level of indication on that this related to jms. WDYT?

Comment (Kishanthan) [inline modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java]: Ok

File: modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java (hunk 1 above)
Comment (Megala21) [inline modules/ballerina-native/src/main/java/org/ballerinalang/nativeimpl/net/jms/Acknowledge.java]: Fixed with e90dd6f7a0f0e74fc8122015f5b2aaff42fcb81f
