### PR TITLE
Fix #3018 #3020 #3065-Set proper error message for connector init

### LINKED ISSUE #3018: Getting net_write_timeout but mysql server is working properly
I got this error while working with mysql connector

ballerina.lang.errors:Error, message: error occurred during writing the message to the output stream: Application was streaming results when the connection failed. Consider raising value of 'net_write_timeout' on the server.

insert type queries are working but select queries give this error

### PR DESCRIPTION
**Pull request by anupama-pathirage**
When the connector is created in service level and if there is an error with the initialization, instead of the correct error message below error is displayed.

`ballerina: internal error occurred`

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BLangVM.java [hunk 1]
```diff
@@ -3327,17 +3328,18 @@ private void handleError() {
...
-                try {
-                    optionalErrorHandler
-                            .orElseGet(DefaultServerConnectorErrorHandler::getInstance)
-                            .handleError(new BallerinaException(
-                                            BLangVMErrors.getPrintableStackTrace(context.getError())),
-                                    context.getCarbonMessage(), context.getBalCallback());
-                } catch (Exception e) {
-                    logger.error("cannot handle error using the error handler for: " + protocol, e);
+                CarbonMessage carbonMessage = context.getCarbonMessage();
+                if (carbonMessage != null) {
```
Comment (hasithaa) [inline modules/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BLangVM.java]: This logic to invoke server connector error handler, if the execution is initiated from a client. 

If the carbon message is null, that means there is no client involved, hence we can't invoke the server connector error handler.  So we just skip. 

This is not an error condition (carbonMessage == null), as this happens at service init.  Hence it is not required to throw an error.
