### PR TITLE
Fix the issue with getHeader() returning null

### LINKED ISSUE #3917: req.getHeader("name") returns null if header not found
Because of the $subject there is no way to determine whether header exist or not.

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #3917

### CODE REVIEW

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpUtil.java [hunk 1]
```diff
@@ -135,12 +136,12 @@
 
         String headerName = abstractNativeFunction.getStringArgument(context, 0);
         String headerValue = httpCarbonMessage.getHeader(headerName);
```
Comment (hasithaa) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HttpUtil.java]: Still, this can be null.
