### PR TITLE
Fix issue #2485

### LINKED ISSUE #2485: [Dispatcher] Contradictory behviour in resources with same url path and query parameters
**Step1: Without query parameters**
Run following sample code
```
package scenario4;

import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:"/http"}
service contentBasedRouting {
    string connection = "url";

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpGetResource (message m) {
        string resourcePath = "/orders/123";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.get(httpCheck, resourcePath, request);
        string value = "originalGet";
        messages:setStringPayload(response, value);
        reply response;

    }

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpGetResource (message m) {
        string resourcePath = "/orders/orderid";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.delete(httpCheck, resourcePath, request);
        messages:setStringPayload(response, "deleteGet");
        reply response;

    }
}
```
**Step 1 Actual Result:** 
`scenario4/IntegratorService.bal:54: redeclared symbol 'httpGetResource' `

**Step 2: With query parameter, same resource name, same resource uri**
Run the following sample code

```
package scenario4;

import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:"/http"}
service contentBasedRouting {
    string connection = "url";

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpGetResource (message m) {
        string resourcePath = "/orders/123";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.get(httpCheck, resourcePath, request);
        string value = "originalGet";
        messages:setStringPayload(response, value);
        reply response;

    }

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpGetResource (message m, @http:QueryParam {value:"orderid"}string orderid) {
        string resourcePath = "/orders/orderid";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.delete(httpCheck, resourcePath, request);
        messages:setStringPayload(response, "deleteGet");
        reply response;

    }
}
```
**Step 2 Actual Result:** 
`Services deployed without a problem`

**Step 3: Different resource names, same resource uri, query parameter**
Run the following sample code

```
package scenario4;

import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:"/http"}
service contentBasedRouting {
    string connection = "url";

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpGetResource (message m) {
        string resourcePath = "/orders/123";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.get(httpCheck, resourcePath, request);
        string value = "originalGet";
        messages:setStringPayload(response, value);
        reply response;

    }

    @http:GET {}
    @http:Path {value:"/callGet"}
    resource httpDGetResource (message m, @http:QueryParam {value:"orderid"}string orderid) {
        string resourcePath = "/orders/orderid";
        string headerValue;
        message response;
        message request = m;
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = http:ClientConnector.delete(httpCheck, resourcePath, request);
        messages:setStringPayload(response, "deleteGet");
        reply response;

    }
}
```
**Step 3 Acutal Result:** 
`ballerina: deploying service(s) in 'scenario4'
ballerina: seems two resources have the same addressable URI
`

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #2485

### CODE REVIEW

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java [hunk 1]
```diff
@@ -187,8 +187,13 @@ public void setResource(HttpResource newResource) {
 
     abstract char getFirstCharacter();
 
-    private Node isAlreadyExist(String token, List<Node> childList) {
+    private Node getExistingChildNode(Node prospectiveChild, String token, List<Node> childList) {
+        boolean isParamType = prospectiveChild instanceof Expression;
+
         for (Node node : childList) {
+            if (isParamType && node instanceof Expression) {
```
Comment (shafreenAnfar) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java]: Let's change the name of the variable node.

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java [hunk 2]
```diff
@@ -187,10 +187,15 @@ public void setResource(HttpResource newResource) {
 
     abstract char getFirstCharacter();
 
-    private Node isAlreadyExist(String token, List<Node> childList) {
-        for (Node node : childList) {
-            if (node.getToken().equals(token)) {
-                return node;
+    private Node getExistingChildNode(Node prospectiveChild, String token, List<Node> childList) {
```
Comment (shafreenAnfar) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java]: Shall we say getMatchingChildNode

File: modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java [hunk 3]
```diff
@@ -48,7 +48,7 @@ protected Node(String token) {
 
     public Node addChild(String segment, Node childNode) {
```
Comment (shafreenAnfar) [inline modules/ballerina-http/src/main/java/org/ballerinalang/net/uri/parser/Node.java]: Shall we change this method only to take the childNode as the input ?
