### PR TITLE
Handle Concurrent Modification Exceptions while iterating collections

### LINKED ISSUE #4451: Handle Concurrent Modification Exceptions in collections while foreach
**Description:**
Programs like followings will fail due to concurrent modification exceptions. 

```ballerina
function main (string[] args) {
    map m = {a:"1A", b:"2B", c:"3C"};
    foreach k, v in m {
        var val, _ = (string)v;
        if (k == "a") {
            m.remove("c");
        }
    }
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by hasithaa**
This will solve concurrent modification issue while iterating a collection of map and JSON types. 
Resolves #4451

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BJSON.java [hunk 1]
```diff
@@ -296,7 +297,7 @@ public BIterator newIterator() {
                 }
             }
             if (arity == 1) {
-                return new BValue[]{new BJSON(collection.value.get((String) iterator.next()))};
+                return new BValue[]{new BJSON(iterator.next().getValue())};
```
Comment (lafernando) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BJSON.java]: Please fix code formatting here. (how come this is not picked up by checkstyle?)

File: modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BJSON.java [hunk 2]
```diff
@@ -290,24 +291,24 @@ public BIterator newIterator() {
...
-                    return new BValue[]{new BJSON(collection.value.get((int) cursor))};
+                    return new BValue[] {new BJSON(collection.value.get((int) cursor))};
                 } else {
-                    return new BValue[]{new BInteger(cursor), new BJSON(collection.value.get((int) cursor))};
+                    return new BValue[] {new BInteger(cursor), new BJSON(collection.value.get((int) cursor))};
                 }
             }
             if (arity == 1) {
-                return new BValue[]{new BJSON(collection.value.get((String) iterator.next()))};
+                return new BValue[] {new BJSON(iterator.next().getValue())};
```
Comment (lafernando) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BJSON.java]: You've to have another space after "{" :) ..

Comment (hasithaa) [reply modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BJSON.java]: @lafernando: I don't think, it is not required. Even in the check style/google code style sample, that space is not there. 

http://checkstyle.sourceforge.net/config_coding.html#ArrayTrailingComma
https://google.github.io/styleguide/javaguide.html#s4.8.3-arrays
