### PR TITLE
Fix json array not auto-growing issue

### LINKED ISSUE #2850: JSON arrays are not auto-growing
```
json[] j1 = [1,2,3];
json j2 = [1,2,3];

j1[8] = 456;
j2[8] = 456; --> throw arrays index out of bound error.
```

### PR DESCRIPTION
**Pull request by SupunS**
Fix #2850

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/model/util/JSONUtils.java [hunk 1]
```diff
@@ -587,12 +588,17 @@ public static void setArrayElement(BJSON json, long index, BJSON element) {
         }
         
         JsonNode jsonElement = element == null ? null : element.value();
+        ArrayNode arrayNode = ((ArrayNode) jsonNode);
         try {
-            if (jsonNode.size() <= index) {
-                throw BLangExceptionHelper.getRuntimeException(RuntimeErrors.ARRAY_INDEX_OUT_OF_RANGE,
-                    index, jsonNode.size());
+            if (arrayNode.size() <= index) {
```
Comment (sameera-jayasoma) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/util/JSONUtils.java]: Shall we implement the same array growing algorithm here as well?

Comment (SupunS) [inline modules/ballerina-core/src/main/java/org/ballerinalang/model/util/JSONUtils.java]: Here the array implementation is at the Jackson level. Therefore we don't have the control over it and the pointers (such as 'size', etc).
So, if we grow the array at a rate of 1.5, it will cause the array to have null values at the tail.
