### PR TITLE
Fix #3066 - Give proper err msg for incorrect first action arg.

### LINKED ISSUE #3066: Misleading error message for incorrect action definition.
```
connector testConnector () {
    action callTest()(string){
        return "hello";
    }
}
```

Getting `ballerina: 0` error msg for above connector definition. 

**Issue**
correct Connector definition should be the following. 

```
connector testConnector () {
    action callTest(testConnector c)(string){
        return "hello";
    }
}
```
Issue happens, we are not validating size of action parameter defintions in the semenatic analyzier. 

ParameterDef firstParamDef = action.getParameterDefs()[0];

### PR DESCRIPTION
**Pull request by hasithaa**

### CODE REVIEW

File: modules/ballerina-core/src/main/java/org/ballerinalang/util/semantics/SemanticAnalyzer.java [hunk 1]
```diff
@@ -777,10 +777,14 @@ public void visit(BallerinaAction action) {
         }
 
         // First parameter should be of type connector in which these actions are defined.
+        if (action.getParameterDefs().length < 1) {
+            BLangExceptionHelper.throwSemanticError(action, SemanticErrors.INVALID_ACTION_FIRST_PARAMETER,
+                    action.getConnectorDef());
+        }
         ParameterDef firstParamDef = action.getParameterDefs()[0];
         if (firstParamDef.getType() != action.getConnectorDef()) {
```
Comment (lankavitharana) [inline modules/ballerina-core/src/main/java/org/ballerinalang/util/semantics/SemanticAnalyzer.java]: BTW shall we merge these two conditions? And also I think it's better if you can get the error and throw it here instead of throwing it inside BLangExceptionHelper
